title: Jr's Homepage
page-top-title: Jiarui Zhang
top-section-bg-text: A true master is an eternal student
home-subtitle: Yourname&ensp;|&ensp;Jr
copyright-text: "&copy; Jiarui Zhang 2023-2025. All Rights Reserved."
